hertheyhermee

diff --git a/0x10-https_ssl/0-world_wide_web b/0x10-https_ssl/0-world_wide_web
--- a/0x10-https_ssl/0-world_wide_web
+++ b/0x10-https_ssl/0-world_wide_web
@@ -1,27 +1,23 @@
-#!/usr/bin/env bash
-# This bash script retrieves DNS information for a specified domain and subdomain.
-# A script function that checks domain.
-function check_domain {
-	domain_names=("www" "lb-01" "web-01" "web-02")
+#!/bin/bash
 
-	for i in "${domain_names[@]}";
-	do
-		dig "${i}"."$1" | grep -A1 'ANSWER SECTION:' | \
-		awk 'FNR == 2 {printf "The subdomain %s is a %s record and points to %s\n", var, $4, $5}' var="$i"
-	done
-}
-# A script function that checks subdomain
-function check_subdomain {
-	dig "${2}"."$1" | grep -A1 'ANSWER SECTION:' | \
-	awk 'FNR == 2 {printf "The subdomain %s is a %s record and points to %s\n", var, $4, $5}' var="$2"
-}
-# Main script program
-if [ $# -lt 1 ]
-then
-	echo "*** Provide domain name ***"
-elif [ $# -eq 1 ]
-then
-	check_domain "$1";
-else
-	check_subdomain "$1" "$2";
+domain="$1"
+subdomain="$2"
+
+# Define the subdomains and their IP addresses
+subdomains=("www" "lb-01" "web-01" "web-02")
+ip_addresses=("54.210.47.110" "54.210.47.110" "34.198.248.145" "54.89.38.100")
+
+# Check if both domain and subdomain are provided
+if [[ -z "$domain" ]]; then
+    echo "Missing domain argument."
+    exit 1
 fi
+
+# Iterate through subdomains and display information
+for ((i=0; i<${#subdomains[@]}; i++)); do
+    if [[ -z "$subdomain" ]] || [[ "$subdomain" == "${subdomains[i]}" ]]; then
+        record_type=$(dig ${subdomains[i]}.$domain +short -t A | awk '{print $1}')
+        destination=$(dig ${subdomains[i]}.$domain +short -t A | awk '{print $1}')
+        echo "The subdomain ${subdomains[i]} is a $record_type record and points to $destination"
+    fi
+done
